# Generated by Django 3.2.20 on 2023-07-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
